stages:
  - test

variables:
  SELENIUM_VERSION: "4.10.0"
  CONTAINER_MEMORY: "6g"
  SHARED_MEMORY: "4g"

test:
  stage: test
  image: docker:latest  # Docker 실행 환경
  services:
    - docker:dind  # Docker-in-Docker 활성화
  before_script:
    - docker info  # Docker 실행 상태 확인
    - docker-compose build  # Docker 이미지 먼저 빌드
  script:
    - docker images
    - docker-compose up -d  # 컨테이너 실행
    - docker exec test-runner pytest src/tests/ui_tests --html=docker_report.html --self-contained-html
  only:
    - main
