version: "3.8"

services:
  selenium:
    image: selenium/standalone-chrome #selenium python 컨테이너 사용
    container_name: selenium-container
    ports:
      - "4444:4444"
    shm_size: "2g"



  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    command: pytest src/tests/ui_tests --html=ui_test_report.html --self-contained-html