services:
  selenium-hub:
    image: selenium/hub:4.6.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    shm_size: '4gb'

  chrome:
    image: selenium/node-chrome:4.6.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  firefox:
    image: selenium/node-firefox:4.6.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443



  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - .:/app
    working_dir: /app
    command: |
      pytest src/tests/ui_tests --alluredir=allure-results && tail -f /dev/null