services:
  selenium-hub:
    image: selenium/hub:4.6.0
    container_name: selenium-hub
    ports:
      - "5555:4444"
    shm_size: '4gb'
  zap:
    depends_on:
      - selenium-hub
    image: ghcr.io/zaproxy/zaproxy
    ports:
      - "9092:8080"
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080
      -config api.disablekey=true
      -config api.addrs.addr.regex=true
      -config api.addrs.addr.name=.*

  chrome:
    image: selenium/node-chrome:4.6.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  firefox:
    image: selenium/node-firefox:4.6.0
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443



  test-runner:
    build: .
    container_name: test-runner
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - .:/app
    working_dir: /app
    command: |
      pytest src/tests/ui_tests --alluredir=allure-results && tail -f /dev/null