default: dev

env:
  dev:
    base_url: "https://api.themoviedb.org/3"
    api_key: "dummy-api-key-1234"
  staging:
    base_url: "https://api.themoviedb.org/3"
    api_key: "dummy-staging-key-5678"
  prod:
    base_url: "https://api.themoviedb.org/3"
    api_key: "dummy-prod-key-9999"
