name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and tools
        run: pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable  
          
      - name: Download ChromeDriver
        run: |
          mkdir -p /tmp/chromedriver
          wget -q https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /tmp/chromedriver/
          mv /tmp/chromedriver/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver   
       
   
      - name: Run tests
        env:
          CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 --disable-gpu --user-data-dir=/tmp/chrome-user-data"
          DISPLAY: :99         
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x16 &
          pytest --maxfail=5 --disable-warnings

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html