name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and tools
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O /tmp/chromedriver.zip https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.83/linux64/chromedriver-linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          sudo apt-get install -y google-chrome-stable
       
      - name: Debug environment
        run: |
          which chromedriver
          chromedriver --version
          google-chrome --version    

      - name: Run tests
        run: pytest --maxfail=5 --disable-warnings

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.html