name: Zap Security Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p zap-output

      - name: Run ZAP Scan (in container)
        run: |
          docker run --name zapscan \
            zaproxy/zap-stable zap-baseline.py \
            -t https://jsonplaceholder.typicode.com \
            -r /tmp/zap_report.html \
            -J /tmp/zap_report.json \
            -m 5 \
            -z "-config api.addrs.addr.regex=.*"

      - name: Copy report files from container
        run: |
          docker cp zapscan:/tmp/zap_report.html zap-output/zap_report.html
          docker cp zapscan:/tmp/zap_report.json zap-output/zap_report.json
          docker rm zapscan

      - name: Upload ZAP Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output
