name: Zap Security Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Scan
        run: |
          mkdir -p zap-output
          docker run -v ${{ github.workspace }}/zap-output:/zap/wrk \
            zaproxy/zap-stable zap-baseline.py \
            -t https://jsonplaceholder.typicode.com \
            -r zap_report.html \
            -J zap_report.json \
            -m 5 \
            -z "-config api.addrs.addr.regex=.*"

      - name: Upload Zap Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-results
