name: Zap Security Scan

on:
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Scan
        run: |
          docker run --name zap-container \
            zaproxy/zap-stable zap-baseline.py \
            -t https://jsonplaceholder.typicode.com \
            -r /tmp/zap_report.html \
            -J /tmp/zap_report.json \
            -m 5 \
            -z "-config api.addrs.addr.regex=.*"

          docker cp zap-container:/tmp/zap_report.html zap-output/zap_report.html
          docker cp zap-container:/tmp/zap_report.json zap-output/zap_report.json
          docker rm zap-container

      - name: Upload Zap Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-results
