name: Zap Security Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p zap-output

      - name: Run ZAP Scan (autooff)
        run: |
          docker run --name zapscan \
            -- rm \
            - user 1000:1000 \
            -v ${{ github.workspace }}/zap-output:/zap/wrk \
            zaproxy/zap-stable zap-baseline.py \
           -t https://jsonplaceholder.typicode.com \
           -r zap_report.html \
           -J zap_report.json \
           -m 5 \
           -T 3 \
           --autooff \
           -z "-config api.disablekey=true -config api.addrs.addr.name=.*"


      - name: Upload ZAP Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output
